services:
  wa-bot:
    image: wa-bot
    container_name: wa-bot
    ports:
      - "3001:3001"
    volumes:
      # Mount folder auth_session untuk menjaga persistensi pairing sesi WhatsApp
      - ./auth_session:/app/auth_session
      # Mount config.json untuk menjaga persistensi konfigurasi Web UI
      - ./config.json:/app/config.json
    env_file:
      - .env
    environment:
      - TZ=Asia/Jakarta
      - PORT=3001
    restart: always
    networks:
      - proxy-net

networks:
  proxy-net:
    external: true
    name: proxy-net
