version: '3.8'

services:
  wa-bot:
    build: .
    container_name: wa-bot-container
    ports:
      - "3000:3000"
    volumes:
      # Mount folder auth_session untuk menjaga persistensi pairing sesi WhatsApp
      - ./auth_session:/app/auth_session
      # Mount config.json untuk menjaga persistensi konfigurasi Web UI
      - ./config.json:/app/config.json
    env_file:
      - .env
    environment:
      - TZ=Asia/Jakarta
    restart: always
